#!/bin/bash
# MUB-X subscription generator (lib/subscribe.sh).
#
# Renders every client link of one user into static files that nginx serves
# under /sub/<token>/, so one URL imports all nodes into any client:
#
#   links.txt      one share link per line (raw)
#   index.txt      base64 of links.txt - the "generic" subscription format
#                  that v2rayNG, NekoBox, Shadowrocket and friends import
#   clash.yaml     Clash / Mihomo / Clash Verge proxy list
#   singbox.json   sing-box outbounds + selector
#
# The files are regenerated by mubx-sub (user add/remove, update, cron) - no
# runtime component is involved. URLs are https://<DOMAIN>/sub/<token>/links.
# Every link uses the server's own domain as address/SNI, so all of them
# verify against the Let's Encrypt certificate with no client toggles.
#
# Sourced by bin/mubx-sub (and CI). Requires lib/render.sh for the user
# store helpers and lib/common.sh for env loading; jq and openssl are
# provisioned by install.sh.

MUBX_SUB_DIR="${MUBX_SUB_DIR:-/var/www/mubx-sub}"
# Where the per-user SS-2022 pre-shared keys live (overridable for tests).
MUBX_SS2022_DIR="${MUBX_SS2022_DIR:-/etc/mubx/ss2022-keys}"
# Where the per-user subscription tokens live (overridable for tests).
MUBX_SUB_TOKEN_DIR="${MUBX_SUB_TOKEN_DIR:-/etc/mubx/sub-tokens}"

if [ -z "${JQ_PROTO_DEF:-}" ]; then
  if [ -r "$(dirname "${BASH_SOURCE[0]}")/render.sh" ]; then
    source "$(dirname "${BASH_SOURCE[0]}")/render.sh"
  elif [ -r /usr/local/lib/mubx/render.sh ]; then
    source /usr/local/lib/mubx/render.sh
  fi
fi

# --- Hysteria2 port hopping (shared with the DNAT in install.sh) ----------

# The configured hopping range as "start:end" (empty when disabled).
mubx_hy2_hopping_range() { # -> stdout
  local file=/etc/mubx/hy2-hopping.conf
  if [ -r "$file" ]; then
    sed -n 's/^HY2_HOPPING_RANGE=//p' "$file" | head -n 1
  fi
}

# --- Shadowsocks 2022 per-user keys ---------------------------------------

# The per-user SS-2022 pre-shared key: a 32-byte base64 key created once and
# reused (Xray requires exactly 32 bytes of key material for
# 2022-blake3-aes-256-gcm).
mubx_ss2022_psk() { # $1 user name -> psk on stdout
  local name="$1" dir="$MUBX_SS2022_DIR" file psk
  install -d -m 0700 "$dir"
  file="$dir/$name"
  if [ -s "$file" ] && openssl base64 -in "$file" -A 2>/dev/null |
       grep -Eq '^[A-Za-z0-9+/]{43}=$'; then
    cat "$file"
    return 0
  fi
  psk="$(openssl rand -base64 32)"
  printf '%s' "$psk" > "$file"
  chmod 0600 "$file"
  printf '%s' "$psk"
}

# Create SS-2022 keys for every store user (idempotent, called by mubx-sub
# and by the render path through mubx_ss2022_apply's caller).
mubx_ensure_ss2022_keys() {
  local name
  [ -f "$MUBX_USERS_FILE" ] || return 0
  while IFS= read -r name; do
    [ -n "$name" ] || continue
    mubx_ss2022_psk "$name" >/dev/null
  done < <(jq -r '.[].name' "$MUBX_USERS_FILE" 2>/dev/null)
}

# base64url without padding - the form ss:// URIs expect.
mubx_b64url() { # stdin -> stdout
  base64 -w 0 | tr '+/' '-_' | tr -d '='
}

# The per-user subscription token: stored on first generation, stable after
# that so client subscriptions never need re-importing.
mubx_sub_token() { # $1 user name -> token on stdout
  local name="$1" dir="$MUBX_SUB_TOKEN_DIR" file tok
  install -d -m 0700 "$dir"
  file="$dir/$name"
  if [ -s "$file" ]; then
    cat "$file"
    return 0
  fi
  tok="$(openssl rand -hex 16)"
  printf '%s' "$tok" > "$file"
  chmod 0600 "$file"
  printf '%s' "$tok"
}

# --- share-link builders (machine-readable, no card decoration) -----------

mubx_sub_links() { # $1 user  $2 uuid  $3 user index  -> links on stdout
  local user="$1" uuid="$2" idx="$3" dom="$DOMAIN" hy2_range
  # Hysteria 2 (+ port hopping range when configured)
  if mubx_user_has_proto "$user" "hysteria2"; then
    hy2_range="$(mubx_hy2_hopping_range)"
    if [ -n "$hy2_range" ]; then
      printf 'hysteria2://%s@%s:4433/?sni=%s&mport=4433%%2C%s#MUBX-Hysteria2\n' \
        "$HY2_PASS" "$dom" "$dom" "$hy2_range"
    else
      printf 'hysteria2://%s@%s:4433/?sni=%s#MUBX-Hysteria2\n' "$HY2_PASS" "$dom" "$dom"
    fi
  fi
  # Xray WS-family transports over TLS on 443
  if mubx_user_has_proto "$user" "vless_ws_tls"; then
    printf 'vless://%s@%s:443?encryption=none&security=tls&type=ws&host=%s&sni=%s&path=%%2Fvless-ws#MUBX-VLESS-WS\n' \
      "$uuid" "$dom" "$dom" "$dom"
  fi
  if mubx_user_has_proto "$user" "vless_httpupgrade_tls"; then
    printf 'vless://%s@%s:443?encryption=none&security=tls&type=httpupgrade&host=%s&sni=%s&path=%%2Fvless-httpupgrade#MUBX-HTTPUpgrade\n' \
      "$uuid" "$dom" "$dom" "$dom"
  fi
  if mubx_user_has_proto "$user" "vless_xhttp_tls"; then
    printf 'vless://%s@%s:443?encryption=none&security=tls&type=xhttp&host=%s&sni=%s&path=%%2Fvless-xhttp#MUBX-XHTTP\n' \
      "$uuid" "$dom" "$dom" "$dom"
  fi
  if mubx_user_has_proto "$user" "vless_grpc_tls"; then
    printf 'vless://%s@%s:443?encryption=none&security=tls&type=grpc&serviceName=vless-grpc&host=%s&sni=%s#MUBX-VLESS-gRPC\n' \
      "$uuid" "$dom" "$dom" "$dom"
  fi
  if mubx_user_has_proto "$user" "vmess_ws_tls"; then
    printf 'vmess://%s\n' \
      "$(printf '{"v":"2","ps":"MUBX-VMess","add":"%s","port":"443","id":"%s","aid":"0","net":"ws","path":"/vmess-ws","type":"none","host":"%s","tls":"tls","sni":"%s"}' \
        "$dom" "$uuid" "$dom" "$dom" | mubx_b64url)"
  fi
  if mubx_user_has_proto "$user" "trojan_ws_tls"; then
    printf 'trojan://%s@%s:443?security=tls&type=ws&host=%s&sni=%s&path=%%2Ftrojan-ws#MUBX-Trojan\n' \
      "$uuid" "$dom" "$dom" "$dom"
  fi
  # Shadowsocks WS+TLS (legacy aes-256-gcm) on the per-user nginx route
  if mubx_user_has_proto "$user" "ss_ws_tls"; then
    printf 'ss://%s@%s:443/?plugin=v2ray-plugin%%3Btls%%3Bhost%%3D%s%%3Bpath%%3D%%2Fss-%s%%3Bmux%%3D0#MUBX-SS-%s\n' \
      "$(printf 'aes-256-gcm:%s' "$uuid" | base64 -w 0)" "$dom" "$dom" "$user" "$user"
  fi
  # Shadowsocks 2022 WS+TLS on the per-user route (when a key exists)
  if mubx_user_has_proto "$user" "ss_2022"; then
    local psk
    psk="$(mubx_ss2022_psk "$user")"
    if [ -n "$psk" ]; then
      printf 'ss://%s@%s:443/?plugin=v2ray-plugin%%3Btls%%3Bhost%%3D%s%%3Bpath%%3D%%2Fss22-%s%%3Bmux%%3D0#MUBX-SS22-%s\n' \
        "$(printf '2022-blake3-aes-256-gcm:%s' "$psk" | base64 -w 0)" "$dom" "$dom" "$user" "$user"
    fi
  fi
  # Shadowsocks plain TCP on Port 443 (direct, no TLS, multiplexed by HAProxy)
  if mubx_user_has_proto "$user" "ss_tcp"; then
    printf 'ss://%s@%s:443#MUBX-SS-%s-443\n' \
      "$(printf 'aes-256-gcm:%s' "$uuid" | base64 -w 0)" "$dom" "$user"
  fi
  # Shadowsocks plain TCP on the per-user standalone port
  if mubx_user_has_proto "$user" "ss_tcp"; then
    printf 'ss://%s@%s:%s#MUBX-SS-%s-tcp\n' \
      "$(printf 'aes-256-gcm:%s' "$uuid" | base64 -w 0)" \
      "$dom" "$(( ${SS_PLAIN_BASE_PORT:-8388} + idx ))" "$user"
  fi
  # ShadowTLS v3 + SS-2022 (when configured)
  # ShadowTLS v3 + SS-2022 (when configured)
  if mubx_user_has_proto "$user" "shadowtls"; then
    local stls_key
    if [ -n "${SHADOWTLS_PASS:-}" ]; then
      stls_key="$(mubx_ss2022_psk admin 2>/dev/null || true)"
      if [ -n "$stls_key" ]; then
        printf 'ss://%s@%s:443/?plugin=shadow-tls%%3Bhost%%3D%s%%3Bpassword%%3D%s%%3Bversion%%3D3#MUBX-ShadowTLS\n' \
          "$(printf '2022-blake3-aes-256-gcm:%s' "$stls_key" | base64 -w 0)" "$dom" \
          "${SHADOWTLS_SNI:-www.microsoft.com}" "$SHADOWTLS_PASS"
      fi
    fi
  fi
  # Chameleon Universal HTTP Proxy (Ports 8080, 3128, 8888)
  if mubx_user_has_proto "$user" "chameleon"; then
    printf 'http://%s:8080#MUBX-Chameleon-8080\n' "$dom"
    printf 'http://%s:3128#MUBX-Chameleon-3128\n' "$dom"
    printf 'http://%s:8888#MUBX-Chameleon-8888\n' "$dom"
  fi
  # TUIC v5 Native QUIC (UDP 8443)
  if mubx_user_has_proto "$user" "tuic"; then
    printf 'tuic://%s:%s@%s:8443?congestion_control=bbr&alpn=h3&sni=%s&allow_insecure=0#MUBX-TUIC-v5\n' \
      "$uuid" "$uuid" "$dom" "$dom"
  fi
}

# --- Clash (YAML; JSON is a valid YAML subset and Clash parses it) --------

mubx_sub_clash() { # $1 user  $2 uuid  $3 user index -> JSON-YAML proxies on stdout
  local user="$1" uuid="$2" idx="$3" dom="$DOMAIN" hy2_range psk="" adminkey="" user_protos='["all"]'
  if [ -f "${MUBX_USERS_FILE:-/etc/mubx/users.json}" ]; then
    user_protos="$(jq -c --arg n "$user" '[.[] | select(.name == $n) | .protocols // ["all"]] | first // ["all"]' "${MUBX_USERS_FILE:-/etc/mubx/users.json}" 2>/dev/null || echo '["all"]')"
  fi
  hy2_range="$(mubx_hy2_hopping_range)"
  if mubx_user_has_proto "$user" "ss_2022" || mubx_user_has_proto "$user" "ss-2022"; then
    psk="$(mubx_ss2022_psk "$user" 2>/dev/null || true)"
  fi
  if mubx_user_has_proto "$user" "shadowtls"; then
    adminkey="$(mubx_ss2022_psk admin 2>/dev/null || true)"
  fi
  jq -n -c \
    --arg dom "$dom" --arg uuid "$uuid" --arg user "$user" \
    --arg hy2pass "${HY2_PASS:-}" --arg hy2range "$hy2_range" --arg psk "$psk" \
    --arg stls "${SHADOWTLS_PASS:-}" --arg sni "${SHADOWTLS_SNI:-www.microsoft.com}" \
    --arg adminkey "$adminkey" \
    --argjson protos "$user_protos" \
    --argjson ssport "$(( ${SS_PLAIN_BASE_PORT:-8388} + idx ))" \
    --argjson isadmin "$([ "$user" = admin ] && printf 1 || printf 0)" "
    ${JQ_PROTO_DEF}
    def cur_user: {name: \$user, protocols: \$protos};
    def hy2: {
      name: \"MUBX-Hysteria2\", type: \"hysteria2\", server: \$dom, port: 4433,
      password: \$hy2pass, sni: \$dom, \"skip-cert-verify\": false
    } + (if \$hy2range != \"\" then {\"ports\": (\$hy2range | gsub(\":\"; \"-\"))} else {} end);
    def vws(path; name): {
      name: name, type: \"vless\", server: \$dom, port: 443, uuid: \$uuid,
      udp: true, tls: true, servername: \$dom, network: \"ws\",
      \"ws-opts\": {path: path, headers: {Host: \$dom}}
    };
    def ss22: (if (\$psk != \"\" and (cur_user | user_has_proto(\"ss-2022\"))) then [{
      name: \"MUBX-SS22\", type: \"ss\", server: \$dom, port: 443,
      cipher: \"2022-blake3-aes-256-gcm\", password: \$psk, udp: true,
      plugin: \"v2ray-plugin\", \"plugin-opts\": {
        mode: \"websocket\", tls: true, host: \$dom, path: (\"/ss22-\" + \$user), mux: false
      }}] else [] end);
    (if (cur_user | user_has_proto(\"hysteria2\")) then [ hy2 ] else [] end)
    + (if (cur_user | user_has_proto(\"tuic\")) then [{
        name: \"MUBX-TUIC-v5\", type: \"tuic\", server: \$dom, port: 8443,
        uuid: \$uuid, password: \$uuid, \"congestion-controller\": \"bbr\",
        udp: true, tls: true, sni: \$dom, alpn: [\"h3\"], \"skip-cert-verify\": false
      }] else [] end)
    + (if (cur_user | user_has_proto(\"vless-ws\")) then [ vws(\"/vless-ws\"; \"MUBX-VLESS-WS\") ] else [] end)
    + (if (cur_user | user_has_proto(\"vless_grpc_tls\")) then [{
        name: \"MUBX-VLESS-gRPC\", type: \"vless\", server: \$dom, port: 443,
        uuid: \$uuid, udp: true, tls: true, servername: \$dom, network: \"grpc\",
        \"grpc-opts\": {\"grpc-service-name\": \"vless-grpc\"}
      }] else [] end)
    + (if (cur_user | user_has_proto(\"vless-httpupgrade\")) then [{
        name: \"MUBX-HTTPUpgrade\", type: \"vless\", server: \$dom, port: 443,
        uuid: \$uuid, udp: true, tls: true, servername: \$dom, network: \"ws\",
        \"ws-opts\": {path: \"/vless-httpupgrade\", headers: {Host: \$dom}}
      }] else [] end)
    + (if (cur_user | user_has_proto(\"vmess-ws\")) then [{
        name: \"MUBX-VMess\", type: \"vmess\", server: \$dom, port: 443,
        uuid: \$uuid, alterId: 0, cipher: \"auto\", udp: true, tls: true,
        servername: \$dom, network: \"ws\",
        \"ws-opts\": {path: \"/vmess-ws\", headers: {Host: \$dom}}
      }] else [] end)
    + (if (cur_user | user_has_proto(\"trojan-ws\")) then [{
        name: \"MUBX-Trojan\", type: \"trojan\", server: \$dom, port: 443,
        password: \$uuid, udp: true, tls: true, sni: \$dom, network: \"ws\",
        \"ws-opts\": {path: \"/trojan-ws\", headers: {Host: \$dom}}
      }] else [] end)
    + (if (cur_user | user_has_proto(\"ss-ws\")) then [{
        name: \"MUBX-SS\", type: \"ss\", server: \$dom, port: 443,
        cipher: \"aes-256-gcm\", password: \$uuid, udp: true,
        plugin: \"v2ray-plugin\", \"plugin-opts\": {
          mode: \"websocket\", tls: true, host: \$dom, path: (\"/ss-\" + \$user), mux: false
        }
      }] else [] end)
    + ss22
    + (if (\$stls != \"\" and (cur_user | user_has_proto(\"shadowtls\"))) then [{
        name: \"MUBX-ShadowTLS\", type: \"ss\", server: \$dom, port: 443,
        cipher: \"2022-blake3-aes-256-gcm\", password: \$adminkey, udp: false,
        plugin: \"shadow-tls\", \"plugin-opts\": {
          version: 3, password: \$stls, host: \$sni
        }
      }] else [] end)
    + (if (cur_user | user_has_proto(\"ss-tcp\")) then [{
        name: \"MUBX-SS-TCP\", type: \"ss\", server: \$dom, port: \$ssport,
        cipher: \"aes-256-gcm\", password: \$uuid, udp: true
      }, {
        name: \"MUBX-SS-443\", type: \"ss\", server: \$dom, port: 443,
        cipher: \"aes-256-gcm\", password: \$uuid, udp: true
      }] else [] end)
    + (if (cur_user | user_has_proto(\"chameleon\")) then [
        {name: \"MUBX-Chameleon-8080\", type: \"http\", server: \$dom, port: 8080},
        {name: \"MUBX-Chameleon-3128\", type: \"http\", server: \$dom, port: 3128},
        {name: \"MUBX-Chameleon-8888\", type: \"http\", server: \$dom, port: 8888}
      ] else [] end)
    | {
        port: 7890,
        \"socks-port\": 7891,
        \"allow-lan\": false,
        mode: \"rule\",
        \"log-level\": \"info\",
        proxies: .,
        \"proxy-groups\": [
          {
            name: \"PROXY\",
            type: \"select\",
            proxies: ([.[].name] + [\"DIRECT\"])
          }
        ],
        rules: [
          \"AND,((DST-PORT,443),(NETWORK,UDP)),REJECT\",
          \"MATCH,PROXY\"
        ]
      }
  "
}

# --- sing-box client outbounds --------------------------------------------

mubx_sub_singbox() { # $1 user  $2 uuid  $3 user index -> sing-box JSON on stdout
  local user="$1" uuid="$2" idx="$3" dom="$DOMAIN" hy2_range psk="" adminkey="" user_protos='["all"]'
  if [ -f "${MUBX_USERS_FILE:-/etc/mubx/users.json}" ]; then
    user_protos="$(jq -c --arg n "$user" '[.[] | select(.name == $n) | .protocols // ["all"]] | first // ["all"]' "${MUBX_USERS_FILE:-/etc/mubx/users.json}" 2>/dev/null || echo '["all"]')"
  fi
  hy2_range="$(mubx_hy2_hopping_range)"
  if mubx_user_has_proto "$user" "ss_2022" || mubx_user_has_proto "$user" "ss-2022"; then
    psk="$(mubx_ss2022_psk "$user" 2>/dev/null || true)"
  fi
  if mubx_user_has_proto "$user" "shadowtls"; then
    adminkey="$(mubx_ss2022_psk admin 2>/dev/null || true)"
  fi
  jq -n \
    --arg dom "$dom" --arg uuid "$uuid" --arg user "$user" \
    --arg hy2pass "${HY2_PASS:-}" --arg hy2range "$hy2_range" \
    --arg psk "$psk" \
    --arg stls "${SHADOWTLS_PASS:-}" --arg sni "${SHADOWTLS_SNI:-www.microsoft.com}" \
    --arg adminkey "$adminkey" \
    --argjson protos "$user_protos" \
    --argjson ssport "$(( ${SS_PLAIN_BASE_PORT:-8388} + idx ))" \
    --argjson isadmin "$([ "$user" = admin ] && printf 1 || printf 0)" "
    ${JQ_PROTO_DEF}
    def cur_user: {name: \$user, protocols: \$protos};
    def hop(h): (if \$hy2range != \"\" then {\"server_ports\": [\"4433\", \$hy2range]} else {} end);
    (
      (if (cur_user | user_has_proto(\"hysteria2\")) then [{
        type: \"hysteria2\", tag: \"MUBX-Hysteria2\", server: \$dom, server_port: 4433,
        password: \$hy2pass, tls: {enabled: true, server_name: \$dom}} + hop(1)
      ] else [] end)
      + (if (cur_user | user_has_proto(\"tuic\")) then [{
        type: \"tuic\", tag: \"MUBX-TUIC-v5\", server: \$dom, server_port: 8443, uuid: \$uuid,
        password: \$uuid, congestion_control: \"bbr\",
        tls: {enabled: true, server_name: \$dom, alpn: [\"h3\"]}
      }] else [] end)
      + (if (cur_user | user_has_proto(\"vless-ws\")) then [{
        type: \"vless\", tag: \"MUBX-VLESS-WS\", server: \$dom, server_port: 443, uuid: \$uuid,
        tls: {enabled: true, server_name: \$dom},
        transport: {type: \"ws\", path: \"/vless-ws\", headers: {Host: \$dom}}
      }] else [] end)
      + (if (cur_user | user_has_proto(\"vless_grpc_tls\")) then [{
        type: \"vless\", tag: \"MUBX-VLESS-gRPC\", server: \$dom, server_port: 443, uuid: \$uuid,
        tls: {enabled: true, server_name: \$dom},
        transport: {type: \"grpc\", service_name: \"vless-grpc\"}
      }] else [] end)
      + (if (cur_user | user_has_proto(\"vless-httpupgrade\")) then [{
        type: \"vless\", tag: \"MUBX-HTTPUpgrade\", server: \$dom, server_port: 443, uuid: \$uuid,
        tls: {enabled: true, server_name: \$dom},
        transport: {type: \"httpupgrade\", path: \"/vless-httpupgrade\", headers: {Host: \$dom}}
      }] else [] end)
      + (if (cur_user | user_has_proto(\"vmess-ws\")) then [{
        type: \"vmess\", tag: \"MUBX-VMess\", server: \$dom, server_port: 443, uuid: \$uuid,
        security: \"auto\", alter_id: 0,
        tls: {enabled: true, server_name: \$dom},
        transport: {type: \"ws\", path: \"/vmess-ws\", headers: {Host: \$dom}}
      }] else [] end)
      + (if (cur_user | user_has_proto(\"trojan-ws\")) then [{
        type: \"trojan\", tag: \"MUBX-Trojan\", server: \$dom, server_port: 443, password: \$uuid,
        tls: {enabled: true, server_name: \$dom},
        transport: {type: \"ws\", path: \"/trojan-ws\", headers: {Host: \$dom}}
      }] else [] end)
      + (if (cur_user | user_has_proto(\"ss-ws\")) then [{
        type: \"shadowsocks\", tag: \"MUBX-SS\", server: \$dom, server_port: 443,
        method: \"aes-256-gcm\", password: \$uuid,
        plugin: \"v2ray-plugin\",
        plugin_opts: (\"tls;host=\" + \$dom + \";path=/ss-\" + \$user + \";mux=0\")
      }] else [] end)
      + (if (\$psk != \"\" and (cur_user | user_has_proto(\"ss-2022\"))) then [{
          type: \"shadowsocks\", tag: \"MUBX-SS22\", server: \$dom, server_port: 443,
          method: \"2022-blake3-aes-256-gcm\", password: \$psk,
          plugin: \"v2ray-plugin\",
          plugin_opts: (\"tls;host=\" + \$dom + \";path=/ss22-\" + \$user + \";mux=0\")
      }] else [] end)
      + (if (cur_user | user_has_proto(\"ss-tcp\")) then [{
        type: \"shadowsocks\", tag: \"MUBX-SS-TCP\", server: \$dom, server_port: \$ssport,
        method: \"aes-256-gcm\", password: \$uuid
      }, {
        type: \"shadowsocks\", tag: \"MUBX-SS-443\", server: \$dom, server_port: 443,
        method: \"aes-256-gcm\", password: \$uuid
      }] else [] end)
      + (if (\$stls != \"\" and (cur_user | user_has_proto(\"shadowtls\"))) then [{
          type: \"shadowtls\", tag: \"MUBX-ShadowTLS-wrap\", server: \$dom, server_port: 443,
          version: 3, password: \$stls,
          tls: {enabled: true, server_name: \$sni}
        }, {
          type: \"shadowsocks\", tag: \"MUBX-ShadowTLS\", server: \$dom, server_port: 443,
          method: \"2022-blake3-aes-256-gcm\", password: \$adminkey, detour: \"MUBX-ShadowTLS-wrap\"
        }] else [] end)
      + (if (cur_user | user_has_proto(\"chameleon\")) then [
          {type: \"http\", tag: \"MUBX-Chameleon-8080\", server: \$dom, server_port: 8080},
          {type: \"http\", tag: \"MUBX-Chameleon-3128\", server: \$dom, server_port: 3128},
          {type: \"http\", tag: \"MUBX-Chameleon-8888\", server: \$dom, server_port: 8888}
        ] else [] end)
    ) as \$outbounds |
    {
      outbounds: \$outbounds,
      route: {
        final: (\$outbounds[0].tag // \"direct\"),
        auto_detect_interface: true
      }
    }
  "
}

# --- top-level writer ------------------------------------------------------

# Generate all subscription files for one user. Safe to run repeatedly; the
# token and any SS-2022 keys are created once and reused.
mubx_sub_generate() { # $1 user name
  local user="$1" uuid idx token out links
  [ -n "${DOMAIN:-}" ] || { echo "[!] DOMAIN not loaded; cannot generate subscriptions." >&2; return 1; }
  [ -n "${HY2_PASS:-}" ] || { echo "[!] HY2_PASS not loaded; cannot generate subscriptions." >&2; return 1; }
  # Resolve the user's UUID + store index (mirrors link-gen's resolution).
  uuid="${UUID:-}" idx=0
  if [ -f "$MUBX_USERS_FILE" ]; then
    read -r uuid idx < <(jq -r --arg n "$user" \
      'range(0; length) as $i | .[$i] | select(.name == $n) | [.uuid, $i] | @tsv' \
      "$MUBX_USERS_FILE" 2>/dev/null || true)
    [ -n "$uuid" ] || { echo "[!] No MUB-X user named '$user'." >&2; return 1; }
  elif [ "$user" != "admin" ]; then
    echo "[!] No user store; only 'admin' exists." >&2
    return 1
  fi
  mubx_ensure_ss2022_keys || true
  token="$(mubx_sub_token "$user")"
  out="$MUBX_SUB_DIR/$token"
  install -d -m 0755 "$out"
  links="$(mubx_sub_links "$user" "$uuid" "$idx")"
  printf '%s\n' "$links" > "$out/links.txt"
  printf '%s\n' "$links" | base64 -w 0 > "$out/index.txt"
  cp -f "$out/index.txt" "$out/sub.txt" 2>/dev/null || true
  mubx_sub_clash "$user" "$uuid" "$idx" | jq . > "$out/clash.yaml"
  mubx_sub_singbox "$user" "$uuid" "$idx" | jq . > "$out/singbox.json"

  # Publish OpenVPN profiles if user is authorized
  if mubx_user_has_proto "$user" "openvpn"; then
    if [ -f /etc/openvpn/client/mubx-client-tcp.ovpn ]; then
      cp -f /etc/openvpn/client/mubx-client-tcp.ovpn "$out/openvpn-tcp.ovpn" 2>/dev/null || true
      cp -f /etc/openvpn/client/mubx-client-tcp.ovpn "$out/openvpn-1194.ovpn" 2>/dev/null || true
      cp -f /etc/openvpn/client/mubx-client-tcp.ovpn "$out/mubx-client-tcp.ovpn" 2>/dev/null || true
    fi
    if [ -f /etc/openvpn/client/mubx-client-udp.ovpn ]; then
      cp -f /etc/openvpn/client/mubx-client-udp.ovpn "$out/openvpn-udp.ovpn" 2>/dev/null || true
      cp -f /etc/openvpn/client/mubx-client-udp.ovpn "$out/openvpn-2200.ovpn" 2>/dev/null || true
      cp -f /etc/openvpn/client/mubx-client-udp.ovpn "$out/mubx-client-udp.ovpn" 2>/dev/null || true
    fi
  else
    rm -f "$out"/openvpn*.ovpn "$out"/mubx-client*.ovpn 2>/dev/null || true
  fi

  # Publish WireGuard config if user is authorized
  if mubx_user_has_proto "$user" "wireguard"; then
    if [ -f /etc/wireguard/mubx-client.conf ]; then
      cp -f /etc/wireguard/mubx-client.conf "$out/wireguard.conf" 2>/dev/null || true
      cp -f /etc/wireguard/mubx-client.conf "$out/wireguard-51820.conf" 2>/dev/null || true
      cp -f /etc/wireguard/mubx-client.conf "$out/wg.conf" 2>/dev/null || true
      cp -f /etc/wireguard/mubx-client.conf "$out/mubx-client.conf" 2>/dev/null || true
    fi
  else
    rm -f "$out"/wireguard*.conf "$out"/wg*.conf 2>/dev/null || true
  fi

  chmod 0644 "$out"/* 2>/dev/null || true
  printf 'https://%s/sub/%s/index.txt\n' "$DOMAIN" "$token"
}

