#!/bin/bash
# MUB-X subscription generator (lib/subscribe.sh).
#
# Renders every client link of one user into static files that nginx serves
# under /sub/<token>/, so one URL imports all nodes into any client:
#
#   links.txt      one share link per line (raw)
#   index.txt      base64 of links.txt - the "generic" subscription format
#                  that v2rayNG, NekoBox, Shadowrocket and friends import
#   clash.yaml     Clash / Mihomo / Clash Verge proxy list
#   singbox.json   sing-box outbounds + selector
#
# The files are regenerated by mubx-sub (user add/remove, update, cron) - no
# runtime component is involved. URLs are https://<DOMAIN>/sub/<token>/links.
# Every link uses the server's own domain as address/SNI, so all of them
# verify against the Let's Encrypt certificate with no client toggles.
#
# Sourced by bin/mubx-sub (and CI). Requires lib/render.sh for the user
# store helpers and lib/common.sh for env loading; jq and openssl are
# provisioned by install.sh.

MUBX_SUB_DIR="${MUBX_SUB_DIR:-/var/www/mubx-sub}"
# Where the per-user SS-2022 pre-shared keys live (overridable for tests).
MUBX_SS2022_DIR="${MUBX_SS2022_DIR:-/etc/mubx/ss2022-keys}"
# Where the per-user subscription tokens live (overridable for tests).
MUBX_SUB_TOKEN_DIR="${MUBX_SUB_TOKEN_DIR:-/etc/mubx/sub-tokens}"

# --- Hysteria2 port hopping (shared with the DNAT in install.sh) ----------

# The configured hopping range as "start:end" (empty when disabled).
mubx_hy2_hopping_range() { # -> stdout
  local file=/etc/mubx/hy2-hopping.conf
  if [ -r "$file" ]; then
    sed -n 's/^HY2_HOPPING_RANGE=//p' "$file" | head -n 1
  fi
}

# --- Shadowsocks 2022 per-user keys ---------------------------------------

# The per-user SS-2022 pre-shared key: a 32-byte base64 key created once and
# reused (Xray requires exactly 32 bytes of key material for
# 2022-blake3-aes-256-gcm).
mubx_ss2022_psk() { # $1 user name -> psk on stdout
  local name="$1" dir="$MUBX_SS2022_DIR" file psk
  install -d -m 0700 "$dir"
  file="$dir/$name"
  if [ -s "$file" ] && openssl base64 -in "$file" -A 2>/dev/null |
       grep -Eq '^[A-Za-z0-9+/]{43}=$'; then
    cat "$file"
    return 0
  fi
  psk="$(openssl rand -base64 32)"
  printf '%s' "$psk" > "$file"
  chmod 0600 "$file"
  printf '%s' "$psk"
}

# Create SS-2022 keys for every store user (idempotent, called by mubx-sub
# and by the render path through mubx_ss2022_apply's caller).
mubx_ensure_ss2022_keys() {
  local name
  [ -f "$MUBX_USERS_FILE" ] || return 0
  while IFS= read -r name; do
    [ -n "$name" ] || continue
    mubx_ss2022_psk "$name" >/dev/null
  done < <(jq -r '.[].name' "$MUBX_USERS_FILE" 2>/dev/null)
}

# base64url without padding - the form ss:// URIs expect.
mubx_b64url() { # stdin -> stdout
  base64 -w 0 | tr '+/' '-_' | tr -d '='
}

# The per-user subscription token: stored on first generation, stable after
# that so client subscriptions never need re-importing.
mubx_sub_token() { # $1 user name -> token on stdout
  local name="$1" dir="$MUBX_SUB_TOKEN_DIR" file tok
  install -d -m 0700 "$dir"
  file="$dir/$name"
  if [ -s "$file" ]; then
    cat "$file"
    return 0
  fi
  tok="$(openssl rand -hex 16)"
  printf '%s' "$tok" > "$file"
  chmod 0600 "$file"
  printf '%s' "$tok"
}

# --- share-link builders (machine-readable, no card decoration) -----------

mubx_sub_links() { # $1 user  $2 uuid  $3 user index  -> links on stdout
  local user="$1" uuid="$2" idx="$3" dom="$DOMAIN" hy2_range
  # Hysteria 2 (+ port hopping range when configured)
  hy2_range="$(mubx_hy2_hopping_range)"
  if [ -n "$hy2_range" ]; then
    printf 'hysteria2://%s@%s:4433/?sni=%s&mport=4433%%2C%s#MUBX-Hysteria2\n' \
      "$HY2_PASS" "$dom" "$dom" "$hy2_range"
  else
    printf 'hysteria2://%s@%s:4433/?sni=%s#MUBX-Hysteria2\n' "$HY2_PASS" "$dom" "$dom"
  fi
  # Xray WS-family transports over TLS on 443
  printf 'vless://%s@%s:443?encryption=none&security=tls&type=ws&host=%s&sni=%s&path=%%2Fvless-ws#MUBX-VLESS-WS\n' \
    "$uuid" "$dom" "$dom" "$dom"
  printf 'vless://%s@%s:443?encryption=none&security=tls&type=httpupgrade&host=%s&sni=%s&path=%%2Fvless-httpupgrade#MUBX-HTTPUpgrade\n' \
    "$uuid" "$dom" "$dom" "$dom"
  printf 'vless://%s@%s:443?encryption=none&security=tls&type=xhttp&host=%s&sni=%s&path=%%2Fvless-xhttp#MUBX-XHTTP\n' \
    "$uuid" "$dom" "$dom" "$dom"
  printf 'vless://%s@%s:8443?encryption=none&security=tls&type=tcp&sni=%s#MUBX-VLESS-TLS\n' \
    "$uuid" "$dom" "$dom"
  printf 'vmess://%s\n' \
    "$(printf '{"v":"2","ps":"MUBX-VMess","add":"%s","port":"443","id":"%s","aid":"0","net":"ws","path":"/vmess-ws","type":"none","host":"%s","tls":"tls","sni":"%s"}' \
      "$dom" "$uuid" "$dom" "$dom" | mubx_b64url)"
  printf 'trojan://%s@%s:443?security=tls&type=ws&host=%s&sni=%s&path=%%2Ftrojan-ws#MUBX-Trojan\n' \
    "$uuid" "$dom" "$dom" "$dom"
  # Shadowsocks WS+TLS (legacy aes-256-gcm) on the per-user nginx route
  printf 'ss://%s@%s:443?plugin=v2ray-plugin%%3Btls%%3Bhost%%3D%s%%3Bpath%%3D%%2Fss-%s%%3Bmux%%3D0#MUBX-SS-%s\n' \
    "$(printf 'aes-256-gcm:%s' "$uuid" | mubx_b64url)" "$dom" "$dom" "$user" "$user"
  # Shadowsocks 2022 WS+TLS on the per-user route (when a key exists)
  local psk
  psk="$(mubx_ss2022_psk "$user")"
  if [ -n "$psk" ]; then
    printf 'ss://%s@%s:443?plugin=v2ray-plugin%%3Btls%%3Bhost%%3D%s%%3Bpath%%3D%%2Fss22-%s%%3Bmux%%3D0#MUBX-SS22-%s\n' \
      "$(printf '2022-blake3-aes-256-gcm:%s' "$psk" | mubx_b64url)" "$dom" "$dom" "$user" "$user"
  fi
  # Shadowsocks plain TCP on the per-user port
  printf 'ss://%s@%s:%s#MUBX-SS-%s-tcp\n' \
    "$(printf 'aes-256-gcm:%s' "$uuid" | mubx_b64url)" \
    "$dom" "$(( ${SS_PLAIN_BASE_PORT:-8388} + idx ))" "$user"
  # Raw SS on 443 is the shared primary identity: only for admin.
  if [ "$user" = "admin" ]; then
    printf 'ss://%s@%s:443#MUBX-SS-443\n' \
      "$(printf 'aes-256-gcm:%s' "$(mubx_primary_uuid)" | mubx_b64url)" "$dom"
  fi
}

# --- Clash (YAML; JSON is a valid YAML subset and Clash parses it) --------

mubx_sub_clash() { # $1 user  $2 uuid  $3 user index -> JSON-YAML proxies on stdout
  local user="$1" uuid="$2" idx="$3" dom="$DOMAIN" hy2_range psk
  hy2_range="$(mubx_hy2_hopping_range)"
  psk="$(mubx_ss2022_psk "$user")"
  jq -n -c \
    --arg dom "$dom" --arg uuid "$uuid" --arg user "$user" \
    --arg hy2pass "${HY2_PASS:-}" --arg hy2range "$hy2_range" --arg psk "$psk" \
    --arg stls "${SHADOWTLS_PASS:-}" --arg sni "${SHADOWTLS_SNI:-www.microsoft.com}" \
    --arg adminkey "$(mubx_ss2022_psk admin)" \
    --argjson ssport "$(( ${SS_PLAIN_BASE_PORT:-8388} + idx ))" \
    --argjson isadmin "$([ "$user" = admin ] && printf 1 || printf 0)" '
    def hy2: {
      name: "MUBX-Hysteria2", type: "hysteria2", server: $dom, port: 4433,
      password: $hy2pass, sni: $dom, "skip-cert-verify": false
    } + (if $hy2range != "" then {"ports": ($hy2range | gsub(":"; "-"))} else {} end);
    def vws(path; name): {
      name: name, type: "vless", server: $dom, port: 443, uuid: $uuid,
      udp: true, tls: true, servername: $dom, network: "ws",
      "ws-opts": {path: path, headers: {Host: $dom}}
    };
    def ss22: (if $psk != "" then [{
      name: "MUBX-SS22", type: "ss", server: $dom, port: 443,
      cipher: "2022-blake3-aes-256-gcm", password: $psk, udp: true,
      plugin: "v2ray-plugin", "plugin-opts": {
        mode: "websocket", tls: true, host: $dom, path: ("/ss22-" + $user), mux: false
      }}] else [] end);
    [ hy2 ]
    + [ vws("/vless-ws"; "MUBX-VLESS-WS")
      | .name = "MUBX-VLESS-WS" ]
    + [{
        name: "MUBX-HTTPUpgrade", type: "vless", server: $dom, port: 443,
        uuid: $uuid, udp: true, tls: true, servername: $dom, network: "ws",
        "ws-opts": {path: "/vless-httpupgrade", headers: {Host: $dom}}
      }]
    + [{
        name: "MUBX-VLESS-TLS", type: "vless", server: $dom, port: 8443,
        uuid: $uuid, udp: true, tls: true, servername: $dom, network: "tcp"
      }]
    + [{
        name: "MUBX-VMess", type: "vmess", server: $dom, port: 443,
        uuid: $uuid, alterId: 0, cipher: "auto", udp: true, tls: true,
        servername: $dom, network: "ws",
        "ws-opts": {path: "/vmess-ws", headers: {Host: $dom}}
      }]
    + [{
        name: "MUBX-Trojan", type: "trojan", server: $dom, port: 443,
        password: $uuid, udp: true, tls: true, sni: $dom, network: "ws",
        "ws-opts": {path: "/trojan-ws", headers: {Host: $dom}}
      }]
    + [{
        name: "MUBX-SS", type: "ss", server: $dom, port: 443,
        cipher: "aes-256-gcm", password: $uuid, udp: true,
        plugin: "v2ray-plugin", "plugin-opts": {
          mode: "websocket", tls: true, host: $dom, path: ("/ss-" + $user), mux: false
        }
      }]
    + ss22
    + (if $stls != "" then [{
        name: "MUBX-ShadowTLS", type: "ss", server: $dom, port: 8448,
        cipher: "2022-blake3-aes-256-gcm", password: $adminkey, udp: true,
        plugin: "shadow-tls", "plugin-opts": {
          version: 3, password: $stls, host: $sni
        }
      }] else [] end)
    + [{
        name: "MUBX-SS-TCP", type: "ss", server: $dom, port: $ssport,
        cipher: "aes-256-gcm", password: $uuid, udp: true
      }]
    + (if $isadmin == 1 then [{
        name: "MUBX-SS-443", type: "ss", server: $dom, port: 443,
        cipher: "aes-256-gcm", password: $uuid, udp: true
      }] else [] end)
  '
}

# --- sing-box client outbounds --------------------------------------------

mubx_sub_singbox() { # $1 user  $2 uuid  $3 user index -> sing-box JSON on stdout
  local user="$1" uuid="$2" idx="$3" dom="$DOMAIN" hy2_range psk
  hy2_range="$(mubx_hy2_hopping_range)"
  psk="$(mubx_ss2022_psk "$user")"
  jq -n \
    --arg dom "$dom" --arg uuid "$uuid" --arg user "$user" \
    --arg hy2pass "${HY2_PASS:-}" --arg hy2range "$hy2_range" \
    --arg psk "$psk" \
    --arg stls "${SHADOWTLS_PASS:-}" --arg sni "${SHADOWTLS_SNI:-www.microsoft.com}" \
    --arg adminkey "$(mubx_ss2022_psk admin)" \
    --argjson ssport "$(( ${SS_PLAIN_BASE_PORT:-8388} + idx ))" \
    --argjson isadmin "$([ "$user" = admin ] && printf 1 || printf 0)" '
    def hop(h): (if $hy2range != "" then {"server_ports": ["4433", $hy2range]} else {} end);
    {
      outbounds: (
        [
          {type: "hysteria2", tag: "MUBX-Hysteria2", server: $dom, server_port: 4433,
           password: $hy2pass, tls: {enabled: true, server_name: $dom}} + hop(1),
          {type: "vless", tag: "MUBX-VLESS-WS", server: $dom, server_port: 443, uuid: $uuid,
           tls: {enabled: true, server_name: $dom},
           transport: {type: "ws", path: "/vless-ws", headers: {Host: $dom}}},
          {type: "vless", tag: "MUBX-HTTPUpgrade", server: $dom, server_port: 443, uuid: $uuid,
           tls: {enabled: true, server_name: $dom},
           transport: {type: "httpupgrade", path: "/vless-httpupgrade", headers: {Host: $dom}}},
          {type: "vless", tag: "MUBX-VLESS-TLS", server: $dom, server_port: 8443, uuid: $uuid,
           tls: {enabled: true, server_name: $dom}},
          {type: "vmess", tag: "MUBX-VMess", server: $dom, server_port: 443, uuid: $uuid,
           security: "auto", alter_id: 0,
           tls: {enabled: true, server_name: $dom},
           transport: {type: "ws", path: "/vmess-ws", headers: {Host: $dom}}},
          {type: "trojan", tag: "MUBX-Trojan", server: $dom, server_port: 443, password: $uuid,
           tls: {enabled: true, server_name: $dom},
           transport: {type: "ws", path: "/trojan-ws", headers: {Host: $dom}}},
          {type: "shadowsocks", tag: "MUBX-SS", server: $dom, server_port: 443,
           method: "aes-256-gcm", password: $uuid,
           plugin: "v2ray-plugin",
           plugin_opts: ("tls;host=" + $dom + ";path=/ss-" + $user + ";mux=0")},
          (if $psk != "" then {
            type: "shadowsocks", tag: "MUBX-SS22", server: $dom, server_port: 443,
            method: "2022-blake3-aes-256-gcm", password: $psk,
            plugin: "v2ray-plugin",
            plugin_opts: ("tls;host=" + $dom + ";path=/ss22-" + $user + ";mux=0")
          } else empty end),
          {type: "shadowsocks", tag: "MUBX-SS-TCP", server: $dom, server_port: $ssport,
           method: "aes-256-gcm", password: $uuid}
        ]
        + (if $stls != "" then [{
            type: "shadowtls", tag: "MUBX-ShadowTLS-wrap", server: $dom, server_port: 8448,
            version: 3, password: $stls,
            tls: {enabled: true, server_name: $sni}
          }, {
            type: "shadowsocks", tag: "MUBX-ShadowTLS", server: $dom, server_port: 8448,
            method: "2022-blake3-aes-256-gcm", password: $adminkey, detour: "MUBX-ShadowTLS-wrap"
          }] else [] end)
        + (if $isadmin == 1 then [{
            type: "shadowsocks", tag: "MUBX-SS-443", server: $dom, server_port: 443,
            method: "aes-256-gcm", password: $uuid
          }] else [] end)
      ),
      route: {final: "MUBX-Hysteria2", auto_detect_interface: true}
    }
  '
}

# --- top-level writer ------------------------------------------------------

# Generate all subscription files for one user. Safe to run repeatedly; the
# token and any SS-2022 keys are created once and reused.
mubx_sub_generate() { # $1 user name
  local user="$1" uuid idx token out links
  [ -n "${DOMAIN:-}" ] || { echo "[!] DOMAIN not loaded; cannot generate subscriptions." >&2; return 1; }
  [ -n "${HY2_PASS:-}" ] || { echo "[!] HY2_PASS not loaded; cannot generate subscriptions." >&2; return 1; }
  # Resolve the user's UUID + store index (mirrors link-gen's resolution).
  uuid="${UUID:-}" idx=0
  if [ -f "$MUBX_USERS_FILE" ]; then
    read -r uuid idx < <(jq -r --arg n "$user" \
      'range(0; length) as $i | .[$i] | select(.name == $n) | [.uuid, $i] | @tsv' \
      "$MUBX_USERS_FILE" 2>/dev/null || true)
    [ -n "$uuid" ] || { echo "[!] No MUB-X user named '$user'." >&2; return 1; }
  elif [ "$user" != "admin" ]; then
    echo "[!] No user store; only 'admin' exists." >&2
    return 1
  fi
  mubx_ensure_ss2022_keys || true
  token="$(mubx_sub_token "$user")"
  out="$MUBX_SUB_DIR/$token"
  install -d -m 0755 "$out"
  links="$(mubx_sub_links "$user" "$uuid" "$idx")"
  printf '%s\n' "$links" > "$out/links.txt"
  printf '%s\n' "$links" | base64 -w 0 > "$out/index.txt"
  mubx_sub_clash "$user" "$uuid" "$idx" | jq . > "$out/clash.yaml"
  mubx_sub_singbox "$user" "$uuid" "$idx" | jq . > "$out/singbox.json"
  chmod 0644 "$out"/*
  printf 'https://%s/sub/%s/index.txt\n' "$DOMAIN" "$token"
}
